services:
  database:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_docker}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-symfony}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 30
    networks:
      - gdb_internal_network
    restart:
      always
    volumes:
      - database_data:/var/lib/mysql
  php:
    image: registry.kiora.tech/kiora/crm-gdb_php:0.3.1
    depends_on:
      - database
    environment:
      - APP_ENV=prod
      - DATABASE_URL=${DATABASE_URL:-mysql://symfony:symfony@database:3306/symfony_docker?serverVersion=8.0.40&charset=utf8mb4}
      - MAILER_DSN=${MAILER_DSN:-smtp://mailer:1025}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    networks:
      - gdb_internal_network
    entrypoint: [ "sh", "/var/www/website/entrypoint.sh" ]
    restart:
      always
  nginx:
    image: registry.kiora.tech/kiora/crm-gdb_nginx:0.3.1
    depends_on:
      - php
      - database
    networks:
      - kiora_network
      - gdb_internal_network
    restart:
      always
volumes:
  database_data: { }
  uploads: { }

networks:
  kiora_network:
    external: true
  gdb_internal_network:
    driver: bridge